bid/api/urls.py
# encoding: utf-8
'''
@author: zhushen
@contact: 810909753@q.com
@time: 2018/2/6 9:45
'''
from django.conf.urls import url, include
from rest_framework import routers
from .views import *
import bid.api.views as views

app_name = 'api_bid'

from django.views.decorators.csrf import csrf_exempt

# consumer_router = routers.DefaultRouter()
# consumer_router.register(r'', ConsumerViewSet)
#
# consumer_bid_router = routers.DefaultRouter()
# consumer_bid_router.register(r'', Consumer_bidViewSet)
# identify_code_router = routers.DefaultRouter()
# identify_code_router.register(r'', IdentifyViewSet)
# invite_code_router = routers.DefaultRouter()
# invite_code_router.register(r'', Invite_codeViewSet)
#
# group_router = routers.DefaultRouter()
# hander_router = routers.DefaultRouter()
# hander_router.register(r'', Bid_handerViewSet)
# action_router = routers.DefaultRouter()
# action_router.register(r'', Bid_actionViewSet)
# auction_router = routers.DefaultRouter()
# auction_router.register(r'', Bid_auctionViewSet)
# auction_serverside_router = routers.DefaultRouter()
# auction_serverside_router.register(r'', Bid_auction_serversideViewSet)

# identify_code_serverside_router = routers.DefaultRouter()
# identify_code_serverside_router.register(r'', Identify_serversideViewSet)

# identify_code_list = Identify_serversideViewSet.as_view({'get': 'list', 'post': 'create'})
# identify_code_detail = Identify_serversideViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update',
#                                                                 'put': 'update', 'delete': 'destroy'})
identify_code_serverside_router = routers.DefaultRouter()
identify_code_serverside_router.register(r'', Identify_serversideViewSet)

hander_list = Hander_serversideViewSet.as_view({'get': 'list', 'post': 'create'})
hander_detail = Hander_serversideViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update',
                                                  'put': 'update', 'delete': 'destroy'})

auction_list = Auction_serversideViewSet.as_view({'get': 'list', 'post': 'create'})
auction_detail = Auction_serversideViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update',
                                                    'put': 'update', 'delete': 'destroy'})

record_list = Record_serversideViewset.as_view({'get': 'list', 'post': 'create'})
record_detail = Record_serversideViewset.as_view({'get': 'retrieve', 'patch': 'partial_update',
                                                  'put': 'update', 'delete': 'destroy'})

# manage_urls = [
#     url(r'^ic_manage/', include(identify_code_serverside_router.urls), name='ic_mange'),
#     #  url(r'^ic_manage/$', identify_code_list),
#     # url(r'^ic_manage/(?P<pk>[0-9]+)/', identify_code_detail),
#     url(r'^hd_manage/$', hander_list),
#     url(r'^hd_manage/(?P<pk>[0-9]+)/', hander_detail),
#     url(r'^au_manage/$', auction_list),
#     url(r'^au_manage/(?P<pk>[0-9]+)/', auction_detail),
#     url(r'^rc_manage/$', record_list),
#     url(r'^rc_manage/(?P<pk>[0-9]+)/', record_detail),
# ]

urlpatterns = [
    ##登录
    url('^get_guopaiurl/$', views.get_guopaiurl, name='get_guopaiurl'),
    # url('^monitest/$', views.monitest, name='monitest'),
    url('^get_remotetime/$', views.get_remotetime, name='get_remotetime'),
    url('^bid_firstprice/$', views.bid_firstprice, name='bid_firstprice'),
    url('^bid_logout/$', views.bid_logout, name='bid_logout'),
    url('^bid_keeplogin/$', views.bid_keeplogin, name='bid_keeplogin'),
    ##管理操作

    # url('^identify_code_manage/$', include(identify_code_serverside_router.urls)),
    # url('^identify_code_manage', csrf_exempt( Identify_code_serversideViewSet.as_view({'get':'list', 'put': 'update',
    #
    #                     'patch': 'partial_update', 'delete': 'destroy'})),
    url(r'^ic_manage/', include(identify_code_serverside_router.urls), name='ic_mange'),
    #  url(r'^ic_manage/$', identify_code_list),
    # url(r'^ic_manage/(?P<pk>[0-9]+)/', identify_code_detail),
    url(r'^hd_manage/$', hander_list),
    url(r'^hd_manage/(?P<pk>[0-9]+)/', hander_detail),
    url(r'^au_manage/$', auction_list),
    url(r'^au_manage/(?P<pk>[0-9]+)/', auction_detail),
    url(r'^rc_manage/$', record_list),
    url(r'^rc_manage/(?P<pk>[0-9]+)/', record_detail),
]

bid/urls.py
from django.conf.urls import include, url
from django.urls import path
from .views import create_bid_action, create_bid_auction, batch_create_action, batch_create_auction, bid_login
import bid.views as views

app_name = 'bid'
urlpatterns = [
    url('^create_bid_action/', create_bid_action, name='create_bid_action'),
    url('^create_bid_auction/', create_bid_auction, name='create_bid_auction'),
    url('^batch_create_action/', batch_create_action, name='batch_create_action'),
    url('^batch_create_auction/', batch_create_auction, name='batch_create_auction'),
    url('^bid_login/', bid_login, name='bid_login'),

    ##管理
    url('^manage_bid_auction', views.manage_bid_auction, name='manage_bid_auction'),
    url('^manage_bid_action', views.manage_bid_action, name='manage_bid_action'),
    url('^manage_bid_hander', views.manage_bid_hander, name='manage_bid_hander'),
    url(r'^bid_auction_manage/$', views.Bid_auction_manage, name='Bid_auction_manage'),
    url(r'^bid_action_manage/$', views.Bid_action_manage, name='Bid_action_manage'),


    ##模拟
    path('yanzhengma/<int:pk>', views.yanzhengma, name='yanzhengma'),
    path('answer/<int:pk>', views.answer, name='answer'),
    url('^yanzhengma_refresh/$', views.yanzhengma_refresh, name='yanzhengma_refresh'),
    url('^practice/$', views.practice, name='practice'),
    url('^yanzhengma_count/$', views.get_yanzhengma_count, name='count'),
]

myweb/urls.py
# from django.contrib import admin
# from django.conf.urls import url, include
#
# urlpatterns = [
#     url('admin/', admin.site.urls),
#     url('^account/', include('account.urls'))

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
from django.views.generic.base import TemplateView

from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='myweb API')

urlpatterns = [
    url(r'^schema', schema_view),

    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^bid/', include('bid.urls', namespace='bid')),
    url('', include('news.urls')),  # new
    url('^forums/', include('forums.urls')),
    url('^api/user/', include('account.api.urls')),
    url('^api/bid/', include('bid.api.urls', namespace='api_bid')),
    url(r'^api-token-auth/', obtain_jwt_token),  #获取token
    url(r'^api-token-refresh/', refresh_jwt_token), #刷新token
    url(r'^api-token-verify/', verify_jwt_token), #确认token

    url('^hupaiyihao/', include('hupaiyihao.urls')),

    ##前端
    url(r'^manage/', TemplateView.as_view(template_name="index.html"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bid/api/views.py
# encoding: utf-8
'''
@author: zhushen
@contact: 810909753@q.com
@time: 2018/2/6 9:45
'''

from rest_framework import viewsets, status
from bid.api.serializers import *
from bid.models import *
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.decorators import detail_route, list_route
from rest_framework import generics
from django_filters.rest_framework import DjangoFilterBackend
import django_filters
import json
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from bid.api.permissions import CanBid
from django.shortcuts import get_object_or_404
import time
from tools.tasks import reset_identify_code
from tools.utils import init_variable
from tools.utils import random_str
from django.core import serializers

import logging

logger = logging.getLogger(__name__)


class Hander_serversideViewSet(viewsets.ViewSet):
    queryset = Bid_hander.objects.all()
    permission_classes = (permissions.IsAuthenticated,)

    #
    def list(self, request):
        try:
            print("fdsfsfsfsfs")
            data = request.query_params
            handers = query_hander_by_args(data)  # 带参数查询
            serializer = Bid_handerSerializer(handers['items'], many=True)
            result = dict()
            result['rows'] = serializer.data
            result['count'] = handers['count']
            return Response(result, status=status.HTTP_200_OK, template_name=None, content_type=None)
        except Exception as e:
            return Response(e, status=status.HTTP_404_NOT_FOUND, template_name=None, content_type=None)

    def retrieve(self, request, pk=None):
        queryset = Bid_hander.objects.all()
        hander = get_object_or_404(queryset, pk=pk)
        serializer = Bid_handerSerializer(hander)
        return Response(serializer.data)

    def destroy(self, request, pk=None):
        try:
            hander = Bid_hander.objects.get(pk=pk)
            hander.delete()
            return Response(status=status.HTTP_200_OK)
        except:
            return Response(status=status.HTTP_404_NOT_FOUND)

    def update(self, request, pk=None):
        try:
            data = request.data
            hander = Bid_hander.objects.get(pk=pk)
            hander_name = data['hander_name']
            basic_salary = data['basic_salary']
            total_income = data['total_income']
            hander.hander_name = hander_name
            hander.basic_salary = basic_salary
            hander.total_income = total_income
            hander.save()
            return Response(status=status.HTTP_200_OK)
        except:
            return Response(status=status.HTTP_404_NOT_FOUND)

    def partial_update(self, request, pk=None):
        try:
            data = request.data
            hander = Bid_hander.objects.get(pk=pk)
            hander_name = data['hander_name']
            basic_salary = data['basic_salary']
            total_income = data['total_income']
            hander.hander_name = hander_name
            hander.basic_salary = basic_salary
            hander.total_income = total_income
            hander.save()
            return Response(status=status.HTTP_200_OK)
        except:
            return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def create(self, request, *args, **kwargs):
        try:
            data = request.data
            hander_name = data['hander_name']
            basic_salary = data['basic_salary']
            total_income = data['total_income']
            hander = Bid_hander(hander_name=hander_name, basic_salary=basic_salary, total_income=total_income)
            hander.save()
            return Response(status=status.HTTP_200_OK)
        except:
            return Response(status=status.HTTP_404_NOT_FOUND)


class Auction_serversideViewSet(viewsets.ViewSet):
    queryset = Bid_hander.objects.all()
    permission_classes = (permissions.IsAuthenticated,)

    #
    def list(self, request):
        try:
            data = request.query_params
            ##带available 表示 是创建激活码 SELECT下拉表单所用
            available = data.get('available', None)
            if not available or available == '0':
                auctions = query_auction_by_args(data)  # 带参数查询
                serializer = Bid_auctionSerializer(auctions['items'], many=True)
                result = dict()
                result['rows'] = serializer.data
                print(auctions)
                result['count'] = auctions['count']
                return Response(result, status=status.HTTP_200_OK, template_name=None, content_type=None)
            else:
                auctions = query_available_auction()
                serializer = Bid_auctionAvailableSerializer(auctions['items'], many=True)
                result = serializer.data
                return Response(result, status=status.HTTP_200_OK, template_name=None, content_type=None)
        except Exception as e:
            return Response(e, status=status.HTTP_404_NOT_FOUND, template_name=None, content_type=None)

    def retrieve(self, request, pk=None):
        queryset = Bid_auction.objects.all()
        auction = get_object_or_404(queryset, pk=pk)
        serializer = Bid_auctionSerializer(auction)
        return Response(serializer.data)

    def destroy(self, request, pk=None, *args, **kwargs):
        try:
            auction = Bid_auction.objects.get(pk=pk)
            auction.delete()
            return Response(status=status.HTTP_200_OK)
        except:
            return Response(status=status.HTTP_404_NOT_FOUND)

    def update(self, request, pk=None, *args, **kwargs):
        try:
            auction = Bid_auction.objects.get(pk=pk)
            serializer = Bid_auctionSerializer(auction, data=request.data, partial=True)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_200_OK)
        except:
            return Response(status=status.HTTP_404_NOT_FOUND)

    def partial_update(self, request, pk=None, *args, **kwargs):
        try:
            auction = Bid_auction.objects.get(pk=pk)
            serializer = Bid_auctionSerializer(auction, data=request.data, partial=True)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_200_OK)
        except:
            return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def create(self, request, *args, **kwargs):
        try:
            data = request.data
            serializer = Bid_auctionSerializer(data=data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_200_OK)
            else:
                print(serializer.error_messages)
                print(serializer.errors)
                return Response(status=status.HTTP_404_NOT_FOUND)
        except:
            return Response(status=status.HTTP_404_NOT_FOUND)

    # def get_permissions(self):
    #     """
    #     Instantiates and returns the list of permissions that this view requires.
    #     """
    #     if self.action == 'list':
    #         permission_classes = [IsAuthenticated]
    #     else:
    #         permission_classes = [IsAdmin]
    #     return [permission() for permission in permission_classes]


class Action_serversideViewSet(viewsets.ViewSet):
    queryset = Bid_hander.objects.all()
    permission_classes = (permissions.IsAuthenticated,)

    #
    def list(self, request):
        try:
            data = request.query_params
            auctions = query_auction_by_args(data)  # 带参数查询
            serializer = Bid_auctionSerializer(auctions['items'], many=True)
            result = dict()
            result['rows'] = serializer.data
            result['count'] = auctions['count']
            return Response(result, status=status.HTTP_200_OK, template_name=None, content_type=None)
        except Exception as e:
            return Response(e, status=status.HTTP_404_NOT_FOUND, template_name=None, content_type=None)

    def retrieve(self, request, pk=None):
        queryset = Bid_auction.objects.all()
        auction = get_object_or_404(queryset, pk=pk)
        serializer = Bid_auctionSerializer(auction)
        return Response(serializer.data)

    def destroy(self, request, pk=None, *args, **kwargs):
        try:
            auction = Bid_auction.objects.get(pk=pk)
            auction.delete()
            return Response(status=status.HTTP_200_OK)
        except:
            return Response(status=status.HTTP_404_NOT_FOUND)

    def update(self, request, pk=None, *args, **kwargs):
        try:
            data = request.data
            auction = Bid_auction.objects.get(pk=pk)
            auction_name = data['auction_name']
            basic_salary = data['basic_salary']
            total_income = data['total_income']
            auction.auction_name = auction_name
            auction.basic_salary = basic_salary
            auction.total_income = total_income
            auction.save()
            return Response(status=status.HTTP_200_OK)
        except:
            return Response(status=status.HTTP_404_NOT_FOUND)

    def partial_update(self, request, pk=None, *args, **kwargs):
        try:
            data = request.data
            auction = Bid_auction.objects.get(pk=pk)
            auction_name = data['auction_name']
            basic_salary = data['basic_salary']
            total_income = data['total_income']
            auction.auction_name = auction_name
            auction.basic_salary = basic_salary
            auction.total_income = total_income
            auction.save()
            return Response(status=status.HTTP_200_OK)
        except:
            return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def create(self, request, *args, **kwargs):
        try:
            data = request.data

templates/bid/Moni.html
<!DOCTYPE html>
<html>
<head>
    <title>小鲜肉模拟拍牌系统</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/moni.css" rel="stylesheet">
    <script>
        function stop() {
            return false;
        }

        {#document.oncontextmenu = stop;#}
        document.ondragstart = stop;
    </script>
</head>

<body>
<!-- SWFObject's dynamic embed method replaces this alternative HTML content with Flash content when enough
     JavaScript and Flash plug-in support is available. The div is initially hidden so that it doesn't show
     when JavaScript is disabled.
-->


<div id="outer">
    <div style="height:169px;">
        <h2 style="padding: 25px 0px 10px 0;margin-top: 0px;margin-bottom:15px;text-align: center;">小鲜肉全真模拟系统</font>
        </h2>
        <div>
            <span class="btn btn-info" style="margin-left:28px;margin-right:25px;font-size:20px">  查看教程  </span>
            <span class="btn btn-success" style="margin-left:28px;margin-right:25px;font-size:20px" a="/Practice">   验证码练习  </span>
            <span class="btn btn-warning" style="margin-left:28px;margin-right:25px;font-size:20px">  参加考核  </span>
            <span class="btn btn-danger" style="margin-left:28px;margin-right:25px;font-size:20px"> 返回主页  </span>
        </div>
    </div>

    <!--</div>
    <div id='mainbox'>-->
    <div class='leftmainbox'>
        <ul class='toptext'>
            <li>小鲜肉模拟投拍拍卖会</li>
            <li>模拟投放额度:9951</li>
            <li>目前已投标人数</li>
            <li>拍卖会起止时间:10:30至11:30</li>
            <li>首次出价时段:10:30至11:00</li>
            <li>修改出价时段:11:00至11:30</li>
        </ul>

        <ul class='bottomtext'>
            <li><span>&nbsp;&nbsp;目前为修改出价时段</span></li>
            <li><span>系统目前时间:</span><span class="systemtime"></span>

            </li>
            <li><span>目前最低可成交价:</span><span class="leftprice"></span>

            </li>
            <li><span>最低可成交价出价时间:</span><span class="lasttime"></span>

            </li>
            <li><span>目前数据库接受处理价格区间:</span><span class="pricerange"></span>

            </li>
        </ul>
        {#        <button class="ghostbutton"></button>#}

    </div>
    <div class='rightmainbox'>
        <p class='lowestprice'></p>
        <input type="text" id='selfadd' class='useraddprice' checked="checked">
        <input type="text" id='selfwrite' class='userwriteprice' checked="checked">
        <button id='b1'></button>
        <button id='b2'></button>
        <button id='b3'></button>
        <button id='b4'></button>
        <button id='b5'></button>
        <button id='b6'></button>
        <button id='jiajia'></button>
        <button id='chujia'></button>
        <ul class=righttext>
            <li id="li1">您第一次出价</li>
            <li id="li2">出价金额:100</li>
            <li id="li3">出价时间:2017-7-9 10:30:5</li>
            <li>出价方式:网络出价</li>
        </ul>

    </div>
    <!--隐藏对话框  验证码输入框-->
    <div id="dialog-form">
        <div class='identify'>
            <div id="userprice">您的出价为：90000元</div>
            <div id="yanzhengma"></div>
            <input type="text" id='inputyanzhengma' class='inputyanzhengma' checked="checked">
            <p class="question" id="question"></p>
            <div id="refresh">
            </div>
            <button class="confirm"></button>
            <button class="cancel"></button>
        </div>
    </div>
    <!--隐藏对话框 提示验证码请求过于频繁-->
    <div id="info-tooquick">
        <div class='tooquick'>
            <p>您的出价过快</p>
            <button class="middleconfirm"></button>
        </div>
    </div>
    <!--出价验证码错误提示-->
    <div id="info-wrongcode">
        <div class='tooquick'>
            <p>请输入正确的校验码</p>
            <button class="middleconfirm_wrongcode"></button>
        </div>
    </div>
    <!--价格必须为100错误提示-->
    <div id="info-wrongprice">
        <div class='tooquick'>
            <p>投标金额必须为100的正整倍数。</p>
            <button class="middleconfirm_wrongprice"></button>
        </div>
    </div>

    <!--出价处理-->
    <div id="price-form">
        <div class='priceoperation'>
            <span class="progressbar-bg"></span>
            <span class="progressbar"></span>
        </div>
    </div>

    <!--出价成功-->
    <div id="price-right">
        <div class='price_right'>
            <p>出价有效</p>
            <button class="middleconfirm_priceright"></button>
        </div>
    </div>
    <!--出价不在区间-->
    <div id="price-wrong">
        <div class='price-wrong'>
            <p>您的出价不在修改出价区间内，请重新出价</p>
            <button class="middleconfirm_pricewrong"></button>
        </div>
    </div>
    <!--出价超时-->
    <div id="outoftime">
        <div class='outoftime'>
            <p>您的出价超出截止时间</p>
            <button class="middleconfirm_outoftime"></button>
        </div>
    </div>
    <!--结果提示-->
    <div id="info-result-failure">
        <div class='tooquick'>
            <p>很遗憾，你没有中标</p>
            <button class="middleconfirmfailure"></button>
        </div>
    </div>
    <div id="info-result-success">
        <div class='tooquick'>
            <p>恭喜你，中标了</p>
            <button class="middleconfirmsuccess"></button>
        </div>
    </div>
    <div id="final-info">
        <div class='final-info'>
            <div class='finaltext'>本次拍牌结束啦,请关注我们小鲜肉。<br>任何问题可以联系我们</div>

        </div>
    </div>
</div>


<script src="https://cdn.bootcss.com/jquery/1.9.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/jqueryui/1.10.4/jquery-ui.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>

</script>

<script src="/static/js/moni.js"></script>


</body>

</html>

templates/bid/batch_create_action.html
{% extends 'includes/base.html' %}
{% block content %}
    <div class="container">
        <h2>批量创建策略</h2>
        <form action="/bid/batch_create_action/" method="post" enctype="multipart/form-data">{% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <input type="submit" value="Submit" class="btn-default"/>
        </form>
    </div>
{% endblock %}

templates/bid/batch_create_auction.html
{% extends 'includes/base.html' %}
{% block content %}
    <div class="container">
        <h2>批量创建标书</h2>
        <form action="/bid/batch_create_auction/" method="post" enctype="multipart/form-data">{% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <input type="submit" value="Submit" class="btn-default"/>
        </form>
    </div>
{% endblock %}

templates/bid/create_bid_action.html
{% extends 'includes/base.html' %}
{% block content %}
    <div class="container">
        <h2>创建策略</h2>
        <form action="{% url 'bid:create_bid_action' %}" method="post">{% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <input type="submit" value="Submit"/>
        </form>
    </div>
{% endblock %}

templates/bid/create_bid_auction.html
{% extends 'includes/base.html' %}
{% block content %}
    <div class="container">
        <h2>创建标书</h2>
        <form action="{% url 'bid:create_bid_auction' %}" method="post">{% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <input type="submit" value="Submit"  class="btn btn-default"/>
        </form>
    </div>
{% endblock %}

templates/bid/nav.html
<div class="navbar-default navbar-static-top " role="navigation" id="menu">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">沪牌一号</a>
        </div>
        <div class="navbar-collapse collapse">
            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">
                            管理 <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'bid:manage_bid_auction' %}" target="_self">标书</a></li>
                            <li><a href="{% url 'bid:manage_bid_action' %}" target="_self">策略</a></li>
                            <li><a href="{% url 'bid:manage_bid_hander' %}" target="_self">拍手</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">
                            创建 <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'bid:create_bid_action' %}" target="_blank">创建策略</a></li>
                            <li><a href="{% url 'bid:create_bid_auction' %}" target="_blank">创建标书</a></li>
                            <li><a href="{% url 'bid:batch_create_action' %}" target="_blank">批量创建策略</a></li>
                            <li><a href="{% url 'bid:batch_create_auction' %}" target="_blank">批量创建标书</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            帮助 <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="" target="_blank">概述</a></li>
                            <li><a href="" target="_blank">教程</a></li>
                        </ul>
                        <li><a href="{% url 'home' %}">论坛</a>
                    </li>
                </ul>
            {% endif %}
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="">
                            账号 <b class="caret"></b>
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'logout_then_login' %}">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}?next=/">登录</a></li>
                    <li><a href="{% url 'register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

templates/bid/sidebar.html
<ul class="nav nav-pills nav-stacked  .col-md-2">
    <li role="presentation" class="active"><a href="#">Home</a></li>
    <li role="presentation"><a href="#">Profile</a></li>
    <li role="presentation"><a href="#">Messages</a></li>
</ul>