bid/urls.py
from django.conf.urls import include, url
from django.urls import path
from .views import create_bid_action, create_bid_auction, batch_create_action, batch_create_auction, bid_login
import bid.views as views

app_name = 'bid'
urlpatterns = [
    url('^create_bid_action/', create_bid_action, name='create_bid_action'),
    url('^create_bid_auction/', create_bid_auction, name='create_bid_auction'),
    url('^batch_create_action/', batch_create_action, name='batch_create_action'),
    url('^batch_create_auction/', batch_create_auction, name='batch_create_auction'),
    url('^bid_login/', bid_login, name='bid_login'),

    ##管理
    url('^manage_bid_auction', views.manage_bid_auction, name='manage_bid_auction'),
    url('^manage_bid_action', views.manage_bid_action, name='manage_bid_action'),
    url('^manage_bid_hander', views.manage_bid_hander, name='manage_bid_hander'),
    url(r'^bid_auction_manage/$', views.Bid_auction_manage, name='Bid_auction_manage'),
    url(r'^bid_action_manage/$', views.Bid_action_manage, name='Bid_action_manage'),


    ##模拟
    path('yanzhengma/<int:pk>', views.yanzhengma, name='yanzhengma'),
    path('answer/<int:pk>', views.answer, name='answer'),
    url('^yanzhengma_refresh/$', views.yanzhengma_refresh, name='yanzhengma_refresh'),
    url('^practice/$', views.practice, name='practice'),
    url('^yanzhengma_count/$', views.get_yanzhengma_count, name='count'),
]

forums/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('boards/<str:slug>/', views.board_topics, name='board_topics'),
    path('boards/<str:slug>/new/', views.new_topic, name='new_topic'),
    path('boards/<str:slug>/<str:topic_slug>/', views.topic_posts, name='topic_posts'),
    path('boards/<str:slug>/<str:topic_slug>/reply/', views.reply_topic, name='reply_topic'),
    url('^test/$', views.test, name='test'),
    url('^change_profile/$', views.change_profile, name='change_profile')
]

myweb/urls.py
# from django.contrib import admin
# from django.conf.urls import url, include
#
# urlpatterns = [
#     url('admin/', admin.site.urls),
#     url('^account/', include('account.urls'))

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
from django.views.generic.base import TemplateView

from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='myweb API')

urlpatterns = [
    url(r'^schema', schema_view),

    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^bid/', include('bid.urls', namespace='bid')),
    url('', include('news.urls')),  # new
    url('^forums/', include('forums.urls')),
    url('^api/user/', include('account.api.urls')),
    url('^api/bid/', include('bid.api.urls', namespace='api_bid')),
    url(r'^api-token-auth/', obtain_jwt_token),  #获取token
    url(r'^api-token-refresh/', refresh_jwt_token), #刷新token
    url(r'^api-token-verify/', verify_jwt_token), #确认token

    url('^hupaiyihao/', include('hupaiyihao.urls')),

    ##前端
    url(r'^manage/', TemplateView.as_view(template_name="index.html"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forums/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import Truncator
from django.contrib.auth.models import User
from uuslug import slugify
from tools.utils import random_str
import datetime

##版块
class Board(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)
    board_headimage = models.ImageField(upload_to='user_image', default='user_image/user0.jpg')  # 论坛版块头像
    slug = models.SlugField(max_length=30, unique=True, editable=False)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('board_topics', args=[self.slug])

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

    def save(self, *args, **kwargs):
        truncated = Truncator(self.name)
        self.slug = slugify('{0}{1}'.format(self.id, truncated.chars(10)))
        super(Board,self).save(*args, **kwargs)


##主题
class Topic(models.Model):
    ##帖子标题
    id = models.AutoField(primary_key=True)
    subject = models.CharField(max_length=256)
    last_updated = models.DateTimeField(auto_now_add=True)
    ##版块
    board = models.ForeignKey(
        Board,
        on_delete=models.CASCADE,
        related_name='topics',
        null=True,
    )
    ##帖子创建者
    starter = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='topics',
    )
    ##浏览次数
    views = models.PositiveIntegerField(default=0)
    ##slug
    slug = models.SlugField(editable=False, unique=True, max_length=40)
    ######状态管理######
    state = models.CharField(max_length=20, choices=(('hot', '热帖'), ('normal', ' 普通'), ('water', '刷屏'),
                                                     ('attack', '攻击'), ('ad', '广告'), ('illegal', '违规')),
                             default=('normal', '普通'))
    report = models.CharField(max_length=10, null=True, blank=True,
                              choices=(('water', '刷屏'), ('attack', '攻击'), ('ad', '广告'), ('illegal', '违规')))
    agree = models.PositiveIntegerField(default=0)  # 点赞数量，这个与view共同组成热帖参考因子



    def __str__(self):
        return self.subject

    ##获取绝对路径
    def get_absolute_url(self):
        return reverse('topic_posts', kwargs={
            'slug': self.board.slug,
            'topic_slug': self.slug
        })

    ##自动生成slug
    def save(self, *args, **kwargs):
        truncated = Truncator(self.subject)
        self.slug = slugify('{0}{1}'.format(self.id, truncated.chars(10)))
        super(Topic, self).save(*args, **kwargs)


##帖子内容
class Post(models.Model):
    # 内容
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        related_name='+',
    )
    slug = models.SlugField(editable=False, unique=True, max_length=40)

    def __str__(self):
        truncated = Truncator(self.message)
        return truncated.chars(30)

    def save(self, *args, **kwargs):
        truncated = Truncator(self.message)
        self.slug = slugify(truncated.chars(10))
        super(Post, self).save(*args, **kwargs)

##论坛用户
class ForumUser(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='forum_user')
    nickname = models.CharField(max_length=30, unique=True, null=True, blank=True)
    photo = models.ImageField(upload_to='user_image', blank=True, verbose_name='头像')
    signature = models.CharField(max_length=30, blank=True, verbose_name='个性签名', default='这家伙很懒')
    gender = models.SmallIntegerField(default=-1) # choaices=(('1', '男性'), ('0', '女性'), ('-1', '保密')), blank=True)  ##1代表男性， 0代表女性， -1代表未设定
    # 论坛活动数据
    total_topic = models.PositiveIntegerField(default=0, verbose_name='总帖子')
    total_post = models.PositiveIntegerField(default=0, verbose_name='总回复')
    total_agree = models.PositiveIntegerField(default=0, verbose_name='总赞数积分')
    collection = models.ManyToManyField(Topic, verbose_name="收藏", related_name='collection_users', blank=True)

    # 设置5个权限字段，拥有权限者可操作此表(在admin中授权用户)
    class Meta:
        permissions = (('read', '阅读'),
                       ('reply', '回复'),
                       ('post', '发帖'),
                       ('delete', '删除'),
                       ('control', '控制'))

    def save(self, *args, **kwargs):
        self.nickname = self.user.username  ##初始nickname与用户名相同
        super(ForumUser, self).save(*args, **kwargs)

forums/forms.py
from django import forms

from .models import Topic, Post
from django.utils.translation import ugettext_lazy as _




#Add to a form containing a FileField and change the field names accordingly.
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy
from django.conf import settings


class NewTopicForm(forms.Form):
    subject = forms.CharField(label='主题')
    message = forms.CharField(
        widget=forms.Textarea(),
        max_length=4000,
        help_text='最大长度4000个字符',
        label="内容"
    )




class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]
        help_texts = {'message': '最大长度4000个字符'}
        labels = {'message': '内容'}


class Change_profileForm(forms.Form):
    nickname = forms.CharField(max_length=10, widget=forms.widgets.TextInput(attrs={'class': 'form-control'}))
    signature = forms.CharField(max_length=50, widget=forms.widgets.TextInput(attrs={'class': 'form-control'}))
    gender = forms.IntegerField(label="性别", widget=forms.widgets.Select(choices=((1, '男'), (0, '女'), (-1, '保密')),
                                attrs={'class': 'form-control'}), initial=(-1, '保密'))  ##1代表男性， 0代表女性， -1代表未设定
    photo = forms.FileField(label='上传头像')

    def clean_photo(self):
        photo = self.cleaned_data['photo']
        content_type = photo.content_type.split('/')[0]
        if content_type in settings.CONTENT_TYPES:
            if photo._size > int(settings.MAX_PHOTO_SIZE):
                raise forms.ValidationError(ugettext_lazy('Please keep filesize under %s. Current filesize %s') % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(content._size)))
        else:
            raise forms.ValidationError(ugettext_lazy('File type is not supported'))
        return photo

forums/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from django.db.models import Count

from .forms import NewTopicForm, PostForm, Change_profileForm
from .models import Board, Post, Topic, ForumUser

# 导入Paginator,EmptyPage和PageNotAnInteger模块
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponse
from tools.utils import handle_fileupload

##主页，显示所有版块
class BoardListView(ListView):
    template_name = 'forums/home.html'
    model = Board

def home(request):
    boards = Board.objects.all()
    topics = Topic.objects.all()
    count = topics.count()
    if count > 15:
        topics = Topic.objects.order_by('last_updated')[:15]
    context = {'boards': boards, 'topics': topics}
    return render(request=request, template_name='forums/home.html', context=context)




##查看版块帖子
def board_topics(request, slug):
    board = get_object_or_404(Board, slug=slug)
    topics = board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
    p = Paginator(topics, 20)  # 分页，20篇文章一页
    if p.num_pages <= 1:  # 如果文章不足一页
        article_list = topics  # 直接返回所有文章
        data = ''  # 不需要分页按钮
    else:
        page = int(request.GET.get('page', 1))  # 获取请求的文章页码，默认为第一页
        article_list = p.page(page)  # 返回指定页码的页面
        left = []  # 当前页左边连续的页码号，初始值为空
        right = []  # 当前页右边连续的页码号，初始值为空
        left_has_more = False  # 标示第 1 页页码后是否需要显示省略号
        right_has_more = False  # 标示最后一页页码前是否需要显示省略号
        first = False  # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        last = False  # 标示是否需要显示最后一页的页码号。
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:  # 如果请求第1页
            right = page_range[page:page + 2]  # 获取右边连续号码页
            if right[-1] < total_pages - 1:  # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
                # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
                right_has_more = True
            if right[-1] < total_pages:  # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
                # 所以需要显示最后一页的页码号，通过 last 来指示
                last = True
        elif page == total_pages:  # 如果请求最后一页
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]  # 获取左边连续号码页
            if left[0] > 2:
                left_has_more = True  # 如果最左边的号码比2还要大，说明其与第一页之间还有其他页码，因此需要显示省略号，通过 left_has_more 来指示
            if left[0] > 1:  # 如果最左边的页码比1要大，则要显示第一页，否则第一页已经被包含在其中
                first = True
        else:  # 如果请求的页码既不是第一页也不是最后一页
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]  # 获取左边连续号码页
            right = page_range[page:page + 2]  # 获取右边连续号码页
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        data = {  # 将数据包含在data字典中
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page
        }
    return render(request, 'forums/board_topics.html', context={
        'article_list': article_list, 'data': data, 'board': board
    })



##创建主题
@login_required
@permission_required('forums.post')
def new_topic(request, slug):
    board = get_object_or_404(Board, slug=slug)
    user = request.user
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            topic = Topic(subject=cd['subject'],  board=board, starter=user)
            topic.save()
            Post.objects.create(
                message=cd['message'],
                topic=topic,
                created_by=user,
            )
            return redirect('topic_posts', slug=slug, topic_slug=topic.slug)
    else:
        form = NewTopicForm()

    context = {'board': board, 'form': form}
    return render(request, 'forums/new_topic.html', context)

##查看帖子
def topic_posts(request, slug, topic_slug):
    topic = get_object_or_404(Topic, board__slug=slug, slug=topic_slug)
    topic.views += 1
    topic.save()
    context = {'topic': topic}
    return render(request, 'forums/topic_posts.html', context)


##帖子回复
@login_required
@permission_required('forums.post')
def reply_topic(request, slug, topic_slug):
    topic = get_object_or_404(Topic, board__slug=slug, slug=topic_slug)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            return redirect('topic_posts', slug=slug, topic_slug=topic_slug)
    else:
        form = PostForm()
    context = {'topic': topic, 'form': form}
    return render(request, 'forums/reply_topic.html', context)


@login_required
# @permission_required('account.post', login_url='/')  # login_url 跳转的页面
def test(request):
    return HttpResponse("成功")



@login_required
def change_profile(request):
    if request.method == 'POST':
        form = Change_profileForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            nickname = cd['nickname']  ##昵称
            signature = cd['signature']  ##签名
            gender = cd['gender']  ##性别
            photo = request.FILES['photo']
            p = 'user_image'
            newname = handle_fileupload(photo, p)  ##处理上传文件
            ForumUser.objects.filter(user=request.user).update(nickname=nickname, gender=gender,
                                                                       photo=newname, signature=signature)

            context = {'form': form, 'type': 'info', 'information': '修改资料成功'}

            return render(request, 'forums/change_profile.html', context=context )
        else:
            context = {'form': form, 'type': 'error', 'information': '修改资料失败'}
            return render(request, 'forums/change_profile.html', context=context)
    else:
        forum_user = ForumUser.objects.get(user=request.user)
        form = Change_profileForm(
            data={'signature': forum_user.signature, 'gender': forum_user.gender, 'nickname': forum_user.nickname})
        return render(request, 'forums/change_profile.html', context={'form': form})

templates/forums/base_users.html
{% extends 'includes/../bid/base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/users.css' %}">
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="logo text-center my-4">
        <a href="{% url 'home' %}">Forums</a>
    </h1>
    {% block content %}
    {% endblock %}
</div>
{% endblock %}

templates/forums/board_topics.html
{% extends 'includes/forum_base.html' %}

{% block title %}{{ board.name }} {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">首页</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ board.name }}</li>
            </ol>
        </nav>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="mb-4">
            <a href="{% url 'new_topic' board.slug %}" class="btn btn-primary">
                发新帖
            </a>
        </div>
        <table class="table">
            <thead class="thead-blue">
            <tr>
                <th>主题</th>
                <th>楼主</th>
                <th>回复</th>
                <th>浏览</th>
                <th>最后更新</th>
            </tr>
            </thead>
            <tbody>
            {% for topic in article_list %}
                <tr>
                    <td>
                        <a href="{{ topic.get_absolute_url }}">
                            {{ topic.subject }}
                        </a>
                    </td>
                    <td>{{ topic.starter.username }}</td>
                    <td class="align-middle">{{ topic.replies }}</td>
                    <td class="align-middle">{{ topic.views }}</td>
                    <td>{{ topic.last_updated }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% if data %}
            <ul id="pages" class="pagination pagination-sm pagination-xs">
                {% if data.first %}
                    <li><a href="?page=1">1</a></li>
                {% endif %}
                {% if data.left %}
                    {% if data.left_has_more %}
                        <li><span>...</span></li>
                    {% endif %}
                    {% for i in data.left %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                {% endif %}
                <li class="active"><a href="?page={{ data.page }}">{{ data.page }}</a></li>
                {% if data.right %}
                    {% for i in data.right %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                    {% if data.right_has_more %}
                        <li><span>...</span></li>
                    {% endif %}
                {% endif %}
                {% if data.last %}
                    <li><a href="?page={{ data.total_pages }}">{{ data.total_pages }}</a></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>

{% endblock %}

templates/forums/change_profile.html
{% extends "includes/forum_base.html" %}
{% load form_error %}
{% load form_tags %}
{% block head %}
    <script>
        {#onchange="showImage();#}

        function showImage() {
            if ($("#id_photo").value != "") {
                $("#show_photo").src = "";
            }
        }
    </script>
{% endblock head %}

{% block title %}Log-in{% endblock %}
{% block content %}
    <div class="container">
        <h1>修改个人资料</h1>

        {% flash_infomation type information %}

        <div class="container">
            <form name="loginform" method="post" action="" enctype="multipart/form-data">         {% csrf_token %}
                <div class="form-group ">
                    <label for="id_nickname">昵称：</label>
                    <p>{{ form.nickname }}
                        {% error_msg error.nickname %}
                </div>
                <div class="form-group">
                    <label for="id_gender">性别</label>
                    <p>{{ form.gender }}
                        {% error_msg error.gender %}
                    </p>
                </div>
                <div class="form-group">
                    <label for="id_signature">个性签名</label>
                    <p>{{ form.signature }}
                        {% error_msg error.signature %}
                    </p>
                </div>
                <div class="form-group">
                    <label for="id_photo">头像</label>
                    <p>{{ form.photo }}
                        {% error_msg error.photo %}
                    </p>
                    <img id="show_photo" src="/media/{{ user.forum_user.photo }}" alt="图像" class="mr-2 rounded"
                         width="42" height="42">
                </div>

                <div class=" form-group">
                    <button type="submit" class="btn btn-primary btn-block btn-login">
                        <i class="fa fa-sign-in"></i>
                        修改
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block script %}

{% endblock script %}

templates/forums/home.html
{% extends 'includes/forum_base.html' %}

{% block title %}全部版块{% endblock %}
{% block breadcrumb %}
    <div class="container" style="margin-top: 10px">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">首页</li>
            </ol>
        </nav>
    </div>
{% endblock %}
{% block content %}
    <main role="main" class="container">
        {#        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">#}
        {#            <img class="mr-3" src="/media/system_image/logo.jpeg" alt="logo" width="48" height="48">#}
        {#            <div class="lh-100">#}
        {#                <h6 class="mb-0 text-white lh-100">Bootstrap</h6>#}
        {#                <small>Since 2011</small>#}
        {#            </div>#}
        {#        </div>#}

        <div class="my-3 p-3 bg-white rounded box-shadow">
            <h6 class="border-bottom border-gray pb-2 mb-0">热门版块</h6>

            {% for board in boards %}

                <div class="media text-muted pt-3" style="align-items: flex-start">
                    <img src="/media/{{ board.board_headimage }}" alt="图像" class="mr-2 rounded" width="42" height="42">

                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <strong class="d-block text-gray-dark"><a
                                href="{{ board.get_absolute_url }}"> {{ board.name }}</a></strong>
                        {{ board.description }}
                    </p>
                    <button type="button" class="btn btn-primary">
                        Profile <span class="badge badge-light">{{ board.get_posts_count }}</span>
                        <span class="sr-only">New</span>
                    </button>

                </div>


            {% endfor %}

            <small class="d-block text-right mt-3">
                <a href="#">更多</a>
            </small>
        </div>

        <div class="my-3 p-3 bg-white rounded box-shadow">


            <h6 class="border-bottom border-gray pb-2 mb-0">热帖</h6>
            {% for topic in topics %}
                <div class="media text-muted pt-3">
                    <img src="/media/{{ topic.starter.forum_user.photo }}" alt="头像" class="mr-2 rounded">
                    <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <div class="d-flex justify-content-between align-items-center w-100">
                            <strong class="text-gray-dark">
                                <a href="{{ topic.get_absolute_url }}">
                                    {{ topic.subject }}
                                </a>
                            </strong>
                            <a href="#">回复</a>
                        </div>
                        <span class="d-block">by {{ topic.starter.forum_user.nickname }}</span>
                    </div>
                </div>
            {% endfor %}

            <small class="d-block text-right mt-3">
                <a href="#">更多</a>
            </small>
        </div>
    </main>




    {##}
    {#    <div class="container">#}
    {##}
    {#        <table class="table">#}
    {#            <thead class="thead">#}
    {#            <tr>#}
    {#                <th>版块</th>#}
    {#                <th>帖子</th>#}
    {#                <th>主题</th>#}
    {#                <th>最后发表</th>#}
    {#            </tr>#}
    {#            </thead>#}
    {#            <tbody>#}
    {#            {% for board in object_list %}#}
    {#                <tr>#}
    {#                    <td>#}
    {#                        <a href="{% url 'board_topics' board.name %}">#}
    {#                            {{ board.name }}#}
    {#                        </a>#}
    {#                        <small class="text-muted d-block" style="font-size:75%">#}
    {#                            {{ board.description }}#}
    {#                        </small>#}
    {#                    </td>#}
    {#                    <td class="align-middle">{{ board.get_posts_count }}</td>#}
    {#                    <td class="align-middle">{{ board.topics.count }}</td>#}
    {#                    <td class="align-middle">#}
    {#                        {% with post=board.get_last_post %}#}
    {#                            {% if post %}#}
    {#                                <small>#}
    {#                                    <a href="{% url 'topic_posts' board.name post.topic.pk %}">#}
    {#                                        {{ post.created_by.username }} 创建于 {{ post.created_at }}#}
    {#                                    </a>#}
    {#                                </small>#}
    {#                            {% else %}#}
    {#                                <small class="text-muted">#}
    {#                                    <em>还没有任何帖子</em>#}
    {#                                </small>#}
    {#                            {% endif %}#}
    {#                        {% endwith %}#}
    {#                    </td>#}
    {#                </tr>#}
    {#            {% endfor %}#}
    {#            </tbody>#}
    {#        </table>#}
    {#    </div>#}

{% endblock %}

templates/forums/new_topic.html
{% extends 'includes/forum_base.html' %}

{% block title %}Create new post{% endblock %}

{% block breadcrumb %}
    <div class="container">
        <ol class="breadcrumb">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'home' %}">主页
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{{ board.get_absolute_url }}">
                            {{ board.name }}
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        发新帖
                    </li>
                </ol>
            </nav>
        </ol>


    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% load crispy_forms_tags %}
        <form method="post" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="container">
                <button type="submit" id="new_topic" class="btn btn-success">提交</button>
            </div>
        </form>
    </div>


{% endblock %}

{% block script %}
    <script>
        $(window).read(function () {
            $('#new_topic').on('click', function () {


            })
        })

    </script>

{% endblock script %}

templates/forums/reply_topic.html
{% extends 'includes/forum_base.html' %}

{% block title %}Post a reply{% endblock %}

{% block breadcrumb %}
    <div class="container">
    <div class="container">
        <ol class="breadcrumb">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'home' %}">主页
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{{ board.get_absolute_url }}">
                            {{ topic.board.name }}
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{{ topic.get_absolute_url }}">
                            {{ topic.subject }}
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        回复
                    </li>
                </ol>
            </nav>
        </ol>

    </div>
{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    <div class="container">
        <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Post</button>
        </form>
    </div>
    {% include 'includes/all_topic_posts.html' %}

{% endblock %}